<?php

use App\Exceptions\ProofException;
use App\Models\Nonce;
use Illuminate\Validation\ValidationException;

// App will request a nonce from the API via POST /nonce, passing in pubkey and device_name
// API will generate a nonce and store it in the database
// API will return the nonce to the app
// App will generate a proof by signing the nonce with the private key associated with the pubkey
// App will send the proof, pubkey, and device_name to the API via POST /login
// API will validate the proof was generated by the private key associated with the pubkey
// API will return a token to the app
// App will store the token in local storage
// App will send the token in the Authorization header for all subsequent requests



// App will request a nonce from the API via POST /api/nonce, passing in pubkey and device_name
// LoginController@nonce creates nonce, saves to nonces table with timestamps and pubkey and device_name, returns nonce to the app
test('app can request a nonce', function () {
    $response = $this->post('/api/nonce', [
        'pubkey' => '987612984762893476234',
        'device_name' => 'test device',
    ]);

    $response->assertStatus(200)
        ->assertJsonStructure(['nonce']);

    $nonce = $response->json('nonce');
    expect($response->json('nonce'))->toBeString();

    // check that the nonce is in the database, associated with the pubkey and device_name and that nonce is recent
    $this->assertDatabaseHas('nonces', [
        'pubkey' => '987612984762893476234',
        'device_name' => 'test device',
        'nonce' => $nonce,
    ]);

    // Check that the nonce is in the database, associated with the pubkey and device_name, and that it is recent
    $nonceRow = Nonce::where([
        'pubkey' => '987612984762893476234',
        'device_name' => 'test device',
        'nonce' => $nonce,
    ])->first();

    expect($nonceRow)->not->toBeNull();
});

test('nonce request without pubkey fails', function () {
    $this->withoutExceptionHandling();
    $this->expectException(ValidationException::class);

    $this->post('/api/nonce', [
        'device_name' => 'test device',
    ]);
});

test('nonce request without device_name fails', function () {
    $this->withoutExceptionHandling();
    $this->expectException(ValidationException::class);

    $this->post('/api/nonce', [
        'pubkey' => 'asoidfjoasidjfisjsdf',
    ]);
});

test('valid user with invalid nonce cannot log in', function () {
    $this->withoutExceptionHandling();

    // assert there are no personal access tokens in database
    $this->expectException(ProofException::class);
    $this->assertDatabaseCount('personal_access_tokens', 0);

    $this->post('/api/login', [
        'device_name' => 'Test Device Name',
        'hash' => 'ae43d1c024412436da0e2a311370a727de05f16a4f4b6889cf9eaaa14e41b932',
        'nonce' => '49casdasfdasdfef43c135240738ccf',
        'pubkey' => '73fd1e67ef2155429f908247be047d500a75b70fe73bbd0130a8312a35b447e7',
        'secp_pubkey' => '0473fd1e67ef2155429f908247be047d500a75b70fe73bbd0130a8312a35b447e7a97b3f845fe2ac988103db2acfd1d5727245ae4b277a1f98507cb85754fadec8',
        'signature' => '304402200facd06d67efc04a944e34c88de32075bad54662fbf9aad5aa902e5e77cf85d002207e94afd5334c7349cd584f8995a11305092a28ff3ab7ef4710fb4c4244aafb76',
    ]);
});

test('valid user can log in via api', function () {
    $nonce = '49c2050ff9587680beab656ac74b361cfc67753208169bdef43c135240738ccf';
    Nonce::factory()->create(['nonce' => $nonce]);
    $this->assertDatabaseCount('nonces', 1);

    // assert there are no personal access tokens in database
    $this->assertDatabaseCount('personal_access_tokens', 0);

    $response = $this->post('/api/login', [
        'device_name' => 'Test Device Name',
        'hash' => 'ae43d1c024412436da0e2a311370a727de05f16a4f4b6889cf9eaaa14e41b932',
        'nonce' => $nonce,
        'pubkey' => '73fd1e67ef2155429f908247be047d500a75b70fe73bbd0130a8312a35b447e7',
        'secp_pubkey' => '0473fd1e67ef2155429f908247be047d500a75b70fe73bbd0130a8312a35b447e7a97b3f845fe2ac988103db2acfd1d5727245ae4b277a1f98507cb85754fadec8',
        'signature' => '304402200facd06d67efc04a944e34c88de32075bad54662fbf9aad5aa902e5e77cf85d002207e94afd5334c7349cd584f8995a11305092a28ff3ab7ef4710fb4c4244aafb76',
    ]);

    // assert that a string token was returned
    $token = $response->json('token');
    expect($token)->toBeString();

    // assert that a new token was created in the database
    $this->assertDatabaseCount('personal_access_tokens', 1);

    $response->assertStatus(200)
        ->assertJsonStructure(['token']);
});

test('login request without pubkey fails', function () {
    $this->withoutExceptionHandling();
    $this->expectException(ValidationException::class);

    $this->post('/api/login', [
        'device_name' => 'test device',
        'hash' => 'ufhjojasdfhoasudhfiuashdfsdf',
        'nonce' => 'asdofsodifjo2i3jfo2',
        'secp_pubkey' => 'asdf23f23f23f2f',
        'signature' => 'f23f23f23f23f23f23f23f',
    ]);
});

test('login request without secp_pubkey fails', function () {
    $this->withoutExceptionHandling();
    $this->expectException(ValidationException::class);

    $this->post('/api/login', [
        'device_name' => 'test device',
        'hash' => 'ufhjojasdfhoasudhfiuashdfsdf',
        'nonce' => 'asdofsodifjo2i3jfo2',
        'pubkey' => 'asdf23f23f23f2f',
        'signature' => 'f23f23f23f23f23f23f23f',
    ]);
});

test('login request without nonce fails', function () {
    $this->withoutExceptionHandling();
    $this->expectException(ValidationException::class);

    $this->post('/api/login', [
        'device_name' => 'test device',
        'hash' => 'ufhjojasdfhoasudhfiuashdfsdf',
        'pubkey' => 'askdfjhaksdjfhkasjdhfkjsadhf',
        'secp_pubkey' => 'asdf23f23f23f2f',
        'signature' => 'f23f23f23f23f23f23f23f',
    ]);
});

test('login request without device_name fails', function () {
    $this->withoutExceptionHandling();
    $this->expectException(ValidationException::class);

    $this->post('/api/login', [
        'hash' => 'ufhjojasdfhoasudhfiuashdfsdf',
        'nonce' => 'asdofsodifjo2i3jfo2',
        'pubkey' => 'askdfjhaksdjfhkasjdhfkjsadhf',
        'secp_pubkey' => 'asdf23f23f23f2f',
        'signature' => 'f23f23f23f23f23f23f23f',
    ]);
});

test('login request without signature fails', function () {
    $this->withoutExceptionHandling();
    $this->expectException(ValidationException::class);

    $this->post('/api/login', [
        'device_name' => 'test device',
        'hash' => 'ufhjojasdfhoasudhfiuashdfsdf',
        'nonce' => 'asdofsodifjo2i3jfo2',
        'pubkey' => 'askdfjhaksdjfhkasjdhfkjsadhf',
        'secp_pubkey' => 'asdf23f23f23f2f',
    ]);
});

test('login request without valid signature fails', function () {
    $this->withoutExceptionHandling();
    $this->expectException(ProofException::class);

    $this->post('/api/login', [
        'device_name' => 'test device',
        'hash' => 'ufhjojasdfhoasudhfiuashdfsdf',
        'nonce' => 'asdofsodifjo2i3jfo2',
        'pubkey' => 'askdfjhaksdjfhkasjdhfkjsadhf',
        'secp_pubkey' => 'asdf23f23f23f2f',
        'signature' => 'f23f23f23f23f23f23f23f',
    ]);
});
